# Number of players in the lobby before determining there are enough people to begin.
players_to_begin: 8
admin_users:
  - Arold
auth_users:
  - Arold
  - eezyHS
  - Ace
  - LocDogTSD
  - GarinTheGoat
  - saultyaf
  - NY_Mets
self_destruct_time: 30.0